version: 2.1
orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Install Docker CLI to build Docker image
      - run:
          name: Install Docker CLI
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh

      # Build Docker image
      - run:
          name: Build Docker Image
          command: docker build -t my_weather_app .

      # Test the Docker image
      - run:
          name: Test Docker Image
          command: |
            docker run my_weather_app -d -p 80:5000 

      # Send test report to Discord
      - discord/notify:
          webhooks:
            - https://discord.com/api/webhooks/1125033221881610250/8FnLgybV6TKEb2ZMfjqrQ7T-wlPmVinY-vRDnh0aHZia4oMilft6BvgbKYelE6EFH6sF
          content: "Weather App Tests Passed! :white_check_mark:"
          status: success
