version: 2.1
orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      # Start Docker service
      - setup_remote_docker

      # Install Docker CLI to build Docker image (optional, usually already installed)
      - run:
          name: Install Docker CLI
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh

      # Build Docker image
      - run:
          name: Build Docker Image
          command: docker build -t my_weather_app .

      # Start the Docker container for the web app
      - run:
          name: Start Web App Container
          command: docker run -d -p 5000:5000 my_weather_app

      # Wait for the web app to be ready (adjust the timeout as needed)
      - run:
          name: Wait for Web App
          command: |
            i=0
            while [ $i -lt 30 ]; do
              sleep 5
              if curl -s http://localhost:5000; then
                break
              fi
              i=$((i+1))
            done

      # Log into the Docker container and check if the app is running on port 5000
      - run:
          name: Check Web App Status
          command: docker exec -it $(docker ps -lq) netstat -tuln | grep 5000

      # Test the Python code using unit-test2.py
      - run:
          name: Test Python Code
          command: python3 -m unittest unit-test2.py

      # Send test report to Discord
      - run:
          name: Send Discord Notification
          command: |
            curl -X POST -H "Content-Type: application/json" -d '{"content":"Weather App Tests Passed! :white_check_mark:"}' "https://discord.com/api/webhooks/1125033221881610250/8FnLgybV6TKEb2ZMfjqrQ7T-wlPmVinY-vRDnh0aHZia4oMilft6BvgbKYelE6EFH6sF"

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build_and_test
